Repository Mintbase/templates, pull requests merged in 2024-11, with the labels that each got.

#199 Update README.md
  starter-next/README.md
Labels: documentation, Review effort [1-5]: 1

#200 switch to api-ref-react, meta images, add biomejs formatter
  coingecko-ai-plugin-advanced/.gitignore
  coingecko-ai-plugin-advanced/README.md
  coingecko-ai-plugin-advanced/app/ai-plugin/route.ts
  coingecko-ai-plugin-advanced/app/api/[...proxy]/route.ts
  coingecko-ai-plugin-advanced/app/api/ai-plugin/route.ts
  coingecko-ai-plugin-advanced/app/components/api-reference.tsx
  coingecko-ai-plugin-advanced/app/layout.tsx
  coingecko-ai-plugin-advanced/app/page.tsx
  coingecko-ai-plugin-advanced/app/route.ts
  coingecko-ai-plugin-advanced/biome.json
  coingecko-ai-plugin-advanced/next.config.mjs
  coingecko-ai-plugin-advanced/package.json
  coingecko-ai-plugin-advanced/pnpm-lock.yaml
  coingecko-ai-plugin-advanced/postcss.config.mjs
  coingecko-ai-plugin-advanced/public/favicon.ico
  coingecko-ai-plugin-advanced/public/icon.svg
  coingecko-ai-plugin-advanced/public/next.svg
  coingecko-ai-plugin-advanced/public/opengraph-image.png
  coingecko-ai-plugin-advanced/public/twitter-image.png
  coingecko-ai-plugin-advanced/public/vercel.svg
  coingecko-ai-plugin-advanced/tailwind.config.ts
  coingecko-ai-plugin-advanced/tsconfig.json
Labels: enhancement, Configuration changes

#202 Update agent_plugins.md
  bounties/agent_plugins.md
Labels: documentation, Review effort [1-5]: 1

#201 fix: simple token drop folder structure
  simple-token-drop/src/app/page.tsx
  simple-token-drop/src/components/Minter.tsx
  simple-token-drop/src/utils/constants.ts
  simple-token-drop/src/utils/serverMint.ts
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#203 add render-charts primitive to coingecko-ai
  coingecko-ai-plugin-advanced/app/api/ai-plugin/route.ts
Labels: enhancement, Review effort [1-5]: 2
