Repository Mintbase/templates, pull requests merged in 2024-09, with the labels that each got.

#180 Revert "Update README.md add Indexer"
  README.md
Labels: documentation, Review effort [1-5]: 1

#181 Update README.md cowswap images
  cowswap-ai-plugin/README.md
Labels: documentation, Review effort [1-5]: 1

#183 update coingecko-ai template & add coingecko-simple
  coingecko-ai-plugin-advanced/.env.example
  coingecko-ai-plugin-advanced/.gitignore
  coingecko-ai-plugin-advanced/README.md
  coingecko-ai-plugin-advanced/app/api/[...proxy]/route.ts
  coingecko-ai-plugin-advanced/app/favicon.ico
  coingecko-ai-plugin-advanced/app/route.ts
  coingecko-ai-plugin-advanced/next.config.mjs
  coingecko-ai-plugin-advanced/package.json
  coingecko-ai-plugin-advanced/pnpm-lock.yaml
  coingecko-ai-plugin-advanced/postcss.config.mjs
  coingecko-ai-plugin-advanced/public/.well-known/ai-plugin.json
  coingecko-ai-plugin-advanced/public/next.svg
  coingecko-ai-plugin-advanced/public/vercel.svg
  coingecko-ai-plugin-advanced/tailwind.config.ts
  coingecko-ai-plugin-advanced/tsconfig.json
  coingecko-ai-plugin-simple/.gitignore
  coingecko-ai-plugin-simple/README.md
  coingecko-ai-plugin-simple/app/api/ai-plugin/route.ts
  coingecko-ai-plugin-simple/app/api/price/route.ts
  coingecko-ai-plugin-simple/app/favicon.ico
  coingecko-ai-plugin-simple/app/route.ts
  coingecko-ai-plugin-simple/bitte.dev.json
  coingecko-ai-plugin-simple/next.config.mjs
  coingecko-ai-plugin-simple/package.json
  coingecko-ai-plugin-simple/pnpm-lock.yaml
  coingecko-ai-plugin-simple/postcss.config.mjs
  coingecko-ai-plugin-simple/public/next.svg
  coingecko-ai-plugin-simple/public/vercel.svg
  coingecko-ai-plugin-simple/tailwind.config.ts
  coingecko-ai-plugin-simple/tsconfig.json
Labels: documentation, enhancement, Configuration changes, Review effort [1-5]: 4

#184 [Bitte Protocol Support] - AI Chat
  ai-chat/README.md
  ai-chat/package.json
  ai-chat/pnpm-lock.yaml
  ai-chat/src/app/layout.tsx
  ai-chat/src/app/page.tsx
  ai-chat/src/components/chat.tsx
  ai-chat/src/components/connect-wallet.tsx
  ai-chat/src/components/providers/BitteWalletProvider.tsx
Labels: documentation, enhancement, Review effort [1-5]: 3

#185 update blogchain project to Bitte
  blogchain/README.md
  blogchain/package.json
  blogchain/pnpm-lock.yaml
  blogchain/src/app/layout.tsx
  blogchain/src/components/app-providers.tsx
  blogchain/src/components/create-blog.tsx
  blogchain/src/components/create-post.tsx
  blogchain/src/components/footer.tsx
  blogchain/src/components/header.tsx
  blogchain/src/components/hero.tsx
  blogchain/src/components/social.tsx
  blogchain/src/components/user-blogs.tsx
  blogchain/src/components/user-posts.tsx
Labels: documentation, enhancement, Review effort [1-5]: 3

#186 Bitte Protocol AI Minter
  ai-minter/README.md
  ai-minter/package.json
  ai-minter/pnpm-lock.yaml
  ai-minter/src/app/page.tsx
  ai-minter/src/components/NearWalletSelector.tsx
  ai-minter/src/components/Provider.tsx
  ai-minter/src/components/Social.tsx
  ai-minter/src/components/Success.tsx
  ai-minter/src/config/setup.ts
  ai-minter/src/hooks/useMint.ts
  blogchain/README.md
Labels: documentation, enhancement, Review effort [1-5]: 3

#188 Bitte Update for starter-next
  starter-next/README.md
  starter-next/package.json
  starter-next/pnpm-lock.yaml
  starter-next/src/app/layout.tsx
  starter-next/src/app/page.tsx
  starter-next/src/components/NearWalletSelector.tsx
  starter-next/src/components/Social.tsx
Labels: documentation, enhancement, Review effort [1-5]: 3

#189 update marketplace template to bitte
  marketplace/README.md
  marketplace/package.json
  marketplace/pnpm-lock.yaml
  marketplace/src/app/layout.tsx
  marketplace/src/app/page.tsx
  marketplace/src/components/BuyModal/BuyModalInfo.tsx
  marketplace/src/components/Landing.tsx
  marketplace/src/components/header.tsx
  marketplace/src/hooks/useStoreNfts.ts
Labels: documentation, enhancement, Review effort [1-5]: 3

#190 bitte update for minter template
  minter/README.md
  minter/package.json
  minter/pnpm-lock.yaml
  minter/src/app/layout.tsx
  minter/src/app/page.tsx
  minter/src/components/NearWalletSelector.tsx
  minter/src/components/Provider.tsx
  minter/src/components/Social.tsx
  minter/src/config/setup.ts
  minter/src/hooks/useMint.ts
Labels: documentation, enhancement, Review effort [1-5]: 3
